name: MacOs test

on:
  push:
    branches:
      - macos-exe
  pull_request:
    branches:
      - main

jobs:
  run_test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

    - name: Run test script
      shell: bash
      run: |
        chmod +x macosTest.sh
        sh macosTest.sh