name: Win test

on:
  push:
    branches:
      - test

jobs:
  run_test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

    - name: Convert Line Endings to Windows
      shell: bash
      working-directory: ./testScripts
      run: |
        if command -v dos2unix &> /dev/null; then
            dos2unix test_win.bat
        else
            echo "dos2unix not found. You might need to install it."
        fi

    - name: Run test script
      shell: cmd
      working-directory: ./testScripts
      run: call test_win.bat

    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-win
        path: testScripts/testResults/
        if-no-files-found: error
        retention-days: 5
